### ISSUE TITLE
self shouldn't be allowed inside of a non-method

### ISSUE THREAD

**Issue by jmarr** [musictheory/oj#107]
Example:
```
@implementation Foo
 var foobar = function( ) {
  return [self bar];
}
@end
```
The `[self bar]` call should not be allowed.

**Comment by iccir** [comment]
That should be a compiler error, as `self` makes no sense in that context.  Implementation-wise, it currently compiles to `this`, but that has never been guaranteed.

**Comment by iccir** [comment]
Added a new `--warn-self-in-non-methods` option, which warns on *any* usage of `self` outside of a non-method.  For JS libraries or pure-JS files, see #113
