### ISSUE TITLE
Does not install through npm currently

### ISSUE THREAD

**Issue by minusbat** [musictheory/oj#131]
Have tried on both BSD and Linux, and the install fails somewhere when trying to install contextify as it tries to recompile node-gyp. I've tried many things, but I'm an Objective-C person not a node one, soI haven't got very far unfortunately! Sorry...

**Comment by minusbat** [comment]
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

**Comment by minusbat** [comment]
AH, just found this....

https://github.com/brianmcd/contextify/issues/205

And apparently it won't be fixed if you look at the booth :-(

**Comment by iccir** [comment]
I just spun up a blank Ubuntu 16.04 LTS linode, installed node 8.9.3 and npm 5.5.1, and did `npm install ojc`. It worked without error.

How are you trying to install it? As far as I know, the dependency tree shouldn't involve `contextify`.

```
└─┬ ojc@2.0.1
  ├── async@1.5.2
  ├── estraverse@4.2.0
  ├── lodash@3.10.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├── node-getopt@0.2.3
  ├── source-map@0.5.7
  ├─┬ temp@0.8.3
  │ ├── os-tmpdir@1.0.2
  │ └── rimraf@2.2.8
  └── typescript@2.0.10
```

**Comment by iccir** [comment]
Oh, were you doing `npm install oj` instead of `npm install ojc`?

**Comment by minusbat** [comment]
Err, yes, that was it.Installs as ojc fine, with a few warnings. sorry!

**Comment by iccir** [comment]
No worries! Glad it's working! :)
