### ISSUE TITLE
Update to Esprima 2.x

### ISSUE THREAD

**Issue by iccir** [musictheory/oj#38]
When Esprima hits 2.0, we should update to it.  This gives us the ability to parse ECMAScript 6.

**Comment by iccir** [comment]
Esprima is now at 2.0.

**Comment by iccir** [comment]
Oops, my comment from Feb 15 was unclear.  It should have read "Esprima has now released 2.0, thus unblocking this issue" rather than suggesting that I had merged in Esprima 2.0.

**Comment by iccir** [comment]
2.6 on 2.0-wip branch.

**Comment by IngwiePhoenix** [comment]
Oh! Awesome news! I'll test the branch when I have some time.

**Comment by iccir** [comment]
2.7 is on the 1.2 branch (name changed from 2.0 due to semver).
