### ISSUE TITLE
OJ and WebPack - issues with var's.

### ISSUE THREAD

**Issue by IngwiePhoenix** [musictheory/oj#48]
Referencing: https://github.com/webpack/webpack/issues/1001#issuecomment-95735860

Could you look at the gist with the output and determine if the issue comes from OJ? As far as I am aware, the `var`s (`var Foo` and `var Bar` in my case) don't actually contain anything, do they?

**Comment by iccir** [comment]
This is correct behavior.  See https://github.com/musictheory/oj#scope-and-class

Specifically, `Foo` may be a variable name used by a global library, hence, the oj compiler will not touch it.  If Foo is an oj class in the current compilation unit, oj then knows that it is a class and will treat it as such.

You can also tell the compiler that `Foo` is a class by using `@class Foo` at the top of your file.

**Comment by IngwiePhoenix** [comment]
Very nice, thanks for that one. :) I am currently saving compiler state between complilations, so I get the correct behaviour.
That, by the way, also fixed my problem. :)

Thanks for your help!
