### ISSUE TITLE
How do I use protocols?

### ISSUE THREAD

**Issue by IngwiePhoenix** [musictheory/oj#57]
Within the `tests/` folder and sneakily snuck in the README, I saw the mention of `@protocol` and its friends `@required` and `@optional`.

How are Protocols used? I tried to do it with `@implementation MyClass <MyProtocol>` but that did not work. I also added `: BaseObject` in the line but I still got an error, that `unrecognized token <` was found...

**Comment by iccir** [comment]
Right now, `@protocol` exists solely to prevent unknown selector messages - there isn't a way for a class to implement a protocol yet.

Let's use this issue to track full `@protocol` support.

**Comment by IngwiePhoenix** [comment]
Okay, works for me. :) I'll keep my protocols around for the time they become useful though. They do not cause parse errors, so no need to ditch them.

**Comment by iccir** [comment]
Added documentation at https://github.com/musictheory/oj/tree/1.2#protocols

**Comment by IngwiePhoenix** [comment]
I saw the commits - already noticed.
I'm soooo excited for 1.2! :)
