### ISSUE TITLE
Major: Investigate per-file passes rather than concatenated

### ISSUE THREAD

**Issue by iccir** [musictheory/oj#66]
Right now, `compiler.js` concatenates all files together and performs a single AST pass, single builder pass, single generator pass, and single modifier pass.  Ideally, each file would be represented by an internal model class, and smaller passes would be performed (as needed, we could cache a lot).

Changes to global identifiers (classes, enums, consts) would still require a complete recompilation.  So would changes to the known method list, when `--warn-unknown-selectors` is turned on.  Hence, you would still need to pass all files into the compiler, but the actual compilation could be faster.

This would be a breaking change (although one unlikely to affect users) and require a MAJOR semver bumb, as it requires each file to be parseable JS.  Right now you can start a function IIFE in one file and close it in another.

**Comment by IngwiePhoenix** [comment]
Starting in one file, and ending in another, might actually be considerable as a bug, making it harder to be debugged too. I tend to "gulp" a closing brace sometimes. Luckily, I hadn't ran into this issue, yet. But, good to know...

**Comment by iccir** [comment]
That's a really good point!  I agree that it's bad behavior and a bug.  I just think it needs a semver major bump (ideally, in the future, semver would explain what MAJOR/MINOR/BUGFIX means for more than just frameworks/libraries :) )

**Comment by iccir** [comment]
On 2.0 branch and it's working great :)
