### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by iccir** [musictheory/oj#70]
1.2 is feature complete.  I just need to do final testing passes.

**Comment by IngwiePhoenix** [comment]
Can't wait for this to come out. :)
Good luck with the testing!

**Comment by IngwiePhoenix** [comment]
Seems like most of the things are on the 2.0 branch.

How stable is 1.2 thus far? Or are you considering moving directly to 2.0 instead?

**Comment by iccir** [comment]
1.2 should be stable.  2.0 has more test time at this point.  I originally envisioned 1.2 as a stepping stone that people could use to test out the more-strict type checker before opting-in to breaking changes.

**Comment by IngwiePhoenix** [comment]
I see. Thats a pretty good plan! In fact, that is what I am looking forward
to do. :)

2015-12-03 10:49 GMT+01:00 Ricci Adams <notifications@github.com>:

**Comment by iccir** [comment]
+ ojc@1.2.0
