### ISSUE TITLE
Major: No longer support pre-ES5 browsers

### ISSUE THREAD

**Issue by iccir** [musictheory/oj#77]
Right now, oj has workarounds for browsers which don't allow "Reserved words as property names" (see [ES5 compatibility table](http://kangax.github.io/compat-table/es5/)).

This includes:
IE8
Safari 5.0
Chrome 6
Opera 10

Going forward, I'd like to officially state that oj generates ES5-compatible code, and drop official support for non-ES5-compatible browsers.

**Comment by iccir** [comment]
The major compatibility issue here is the `class` method, which is both an oj base object selector and a js reserved word.

**Comment by IngwiePhoenix** [comment]
`class` is reserved in ES5, but how about ES6?

**Comment by iccir** [comment]
Still a reserved word, but it's ok: reserved words can be used as property names:

    // Legal in ES5+, error in older browsers
    var o = { class: "Foo" };  console.log(o.class);

See "Reserved Word Usage" here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

**Comment by iccir** [comment]
On 2.0 branch
