### ISSUE TITLE
Calling dynamic methods?

### ISSUE THREAD

**Issue by IngwiePhoenix** [musictheory/oj#92]
One can check for a method to exist like so:

```objective-c
if([inst respondsToSelector:@selector(init)]) {
    // ...
}
```

But is there a way to run a method dynamically?

```objective-c
var method = "doSomething";
if([instance respondsToSelector:@selector(method)]) {
    [instance performBySelector:@selector(method)];
}
```

I see that ojc turns selectors into pseudo objects, for instance

```javascript
if($oj_oj.msgSend($oj_oj._cls.$oj_c_Derp,{ respondsToSelector_: 1 },{ init: 1 })) {
    $oj_oj.msgSend($oj_oj._cls.$oj_c_Derp,{ init: 1 });
}
```

where `{ respondsToSelector_: 1 }` is some kind of selector - at least, that much I understand.

So is it actually possible to call methods dynamically?

**Comment by iccir** [comment]
Same as Obj-C ;)

```
if ([foo respondsToSelector:@selector(doActionWithString:)]) {
    [foo performSelector:@selector(doActionWithString) withObject:"Foo"];
}

**Comment by iccir** [comment]
`performSelect:`
`performSelector:withObject:`
`performSelector:withObject:withObject:`

**Comment by IngwiePhoenix** [comment]
Ohh, okay. I didn't see any public methods on `oj` regarding `performSelector` :). Thanks for the heads-up.

I also tested to see if variable strings work. `method` is treated as the selector constant - disregarding the value it actually holds. So much for that. Again, thanks! :)

**Comment by iccir** [comment]
https://github.com/musictheory/oj#base-class ;)
